### ISSUE TITLE
ValueError: unrecognized engine zarr must be one of: ['netcdf4', 'scipy', 'store']

### ISSUE THREAD

**Issue by Beam-coder** [obidam/ds2-2022#6]
Hello,

When I run this line:

`ds = cat["en4"].to_dask()`

sometimes, no problem; however, sometimes, there's an error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-dbd9e41d9ee1> in <module>()
----> 1 ds = cat["en4"].to_dask()
      2 print("Size of the dataset:", ds.nbytes/1e9,"Gb")
      3 ds

7 frames
/usr/local/lib/python3.7/dist-packages/xarray/backends/plugins.py in get_backend(engine)
    133                 f"backends {installed_engines}. Consider explicitly selecting one of the "
    134                 "installed engines via the ``engine`` parameter, or installing "
--> 135                 "additional IO dependencies, see:\n"
    136                 "http://xarray.pydata.org/en/stable/getting-started-guide/installing.html\n"
    137                 "http://xarray.pydata.org/en/stable/user-guide/io.html"

ValueError: unrecognized engine zarr must be one of: ['netcdf4', 'scipy', 'store']
```

I tried `!pip install xarray[complete]` as https://github.com/pydata/xarray/issues/5395 suggested, but it still didn't work.

**Comment by gmaze** [comment]
If you find that:
> sometimes, no problem; however, sometimes, there's an error:

then it does not seem like an *environment* set-up issue (otherwise it would never work), but rather an *infrastructure* issue

Where do you run your code ?

**Comment by Beam-coder** [comment]
I run on Colab. I tried `!pip install xarray[complete]`. Sorry, I wrote it wrongly in the question.

**Comment by gmaze** [comment]
> then it does not seem like an _environment_ set-up issue (otherwise it would never work), but rather an _infrastructure_ issue

Try to quit and restart your Google Colab instance

**Comment by Beam-coder** [comment]
After clicking "restart runtime...", it works. Thank you!

**Comment by evileleven** [comment]
> 
I use Jupyter notebook. Just try each command about zarr and xarray, but still doesn't work.
Restart kernel work!!!
